#!/usr/bin/env bash
# Create file with PID

echo $$ > /var/run/myscript.pid

# Trap signals
trap "echo Y U no love me?!; exit" SIGINT
trap 'echo "I hate the kill command"; rm "$file"; exit' SIGTERM SIGQUIT

# Loop infinitely
while true
do
  echo "To infinity and beyond"
  sleep 2
done
