#!/usr/bin/env bash
# Displays "To infinity and beyond" indefinitely

trap "echo I am invincible!!!" SIGTERM

while true; do
    echo "To infinity and beyond"
    sleep 2
done &

pid=$!

while true; do
    read -r -p "Enter 'kill' to stop the process: " input
    if [[ "$input" == "kill" ]]; then
        kill "$pid"
        exit
    fi
done
